packages:
  board: !include ../boards/.dev.yaml
  bt: !include ../common/.bt.yaml
  bh1750: !include ../components/.bh1750.yaml

esp32:
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: "3.1"

status_led:
  pin: GPIO2
