packages:
  wifi: !include packages/common/.wifi-iot.yaml
  captive_portal:
    !include {
      file: packages/common/.captive-portal.yaml,
      vars: { device_name: study-luminance },
    }
  device:
    !include {
      file: packages/devices/.luminance.yaml,
      vars:
        {
          device_name: study-luminance,
          device_friendly_name: study-luminance,
          i2c_sda: 21,
          i2c_scl: 22,
          i2c_address: 0x23,
          update_interval: 30s,
        },
    }
