packages:
  wifi: !include packages/common/.wifi-garage-iot.yaml
  captive_portal:
    !include {
      file: packages/common/.captive-portal.yaml,
      vars: { device_name: x1c-bentobox },
    }
  device:
    !include {
      file: packages/devices/.bentobox.yaml,
      vars: { device_name: x1c-bentobox, device_friendly_name: x1c-bentobox },
    }
